version: '3'

services:
  php:
    restart: always
    build: 
      context: .
      dockerfile: ../../../Dockerfile
    container_name: Hedg_Kranevo.php
    volumes:
      - "../../../Project:/var/www/html"
      - "./uploads:/var/www/html/uploads"
      - "./db.php:/var/www/html/db.php"
    depends_on:
      - mysql

  nginx:
    restart: always
    image: nginx:latest
    container_name: Hedg_Kranevo.nginx
    volumes:
      - "../../../Project:/var/www/html"
      - "./uploads:/var/www/html/uploads"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./db.php:/var/www/html/db.php"
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:latest
    container_name: Hedg_Kranevo.mysql
    environment:
      MYSQL_DATABASE: Hedg-Kranevo
      MYSQL_USER: user            
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "../../../db/:/docker-entrypoint-initdb.d"
      - db_data:/var/lib/mysql

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: Hedg_Kranevo.phpma
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 8081:80
    depends_on:
      - mysql

volumes: 
  db_data:
