version: '3'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - "./Project/:/var/www/html"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
     - "./Project/:/var/www/html"
     - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: user            
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db/:/docker-entrypoint-initdb.d"
      - db_data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpma
    environment:
     - PMA_HOST=mysql
     - PMA_PORT=3306
     - MYSQL_ROOT_PASSWORD=root
    ports: 
     - 8081:80
    depends_on:
     - mysql

volumes: 
  db_data:
