version: '3'

services:
  php:
    restart: always
    build: 
      context: .
      dockerfile: ../../../Dockerfile
    container_name: Hedg_zachet.php
    volumes:
      - "../../../Project:/var/www/html"
      - "./uploads:/var/www/html/uploads"
    depends_on:
      - mysql

  nginx:
    restart: always
    image: nginx:latest
    container_name: Hedg_zachet.nginx
    volumes:
      - "../../../Project:/var/www/html"
      - "./uploads:/var/www/html/uploads"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8082:80
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:latest
    container_name: Hedg_zachet.mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: user            
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - "../../../db/:/docker-entrypoint-initdb.d"
      - db_data:/var/lib/mysql 

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: Hedg_zachet.phpma
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 8083:80
    depends_on:
      - mysql

volumes: 
  db_data: